version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: fitness_assistant_db
    environment:
      POSTGRES_DB: fitness_assistant
      POSTGRES_USER: fitness_user
      POSTGRES_PASSWORD: fitness_dev_2024
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - fitness_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fitness_user -d fitness_assistant"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Interface administrativa (opcional)
  adminer:
    image: adminer
    container_name: fitness_assistant_adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  fitness_postgres_data: